### ISSUE TITLE
[PE-D] Edit command for r/ and g/ errors

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-TIC4002-F18-5/tp2#107]
As in the add command r/ and g/ combination flaw, it also exists in edit command:

![image.png](https://raw.githubusercontent.com/gweeyc/ped/main/files/ca28c466-9311-41df-888e-f4cd7c6bcc94.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: gweeyc/ped#4

**Comment by lowyanshuang** [comment]
No gender function in our project. Updated user guide.
