### ISSUE TITLE
[PE-D] Add command arg t/TAG not working right

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-TIC4002-F18-5/tp2#109]
Add command t/tag feature not working right at all - tag names should not be alphanumeric:

![image.png](https://raw.githubusercontent.com/gweeyc/ped/main/files/fe3cf941-0ecb-4e92-9d7c-e45d4ca1d56f.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: gweeyc/ped#6

**Comment by lowyanshuang** [comment]
g/ is not recognise as a function therefore it is consider as part of the tag 'colleagues g/male'

**Comment by lowyanshuang** [comment]
No gender function in our project. Updated user guide.
